ARG BASE_IMAGE=livepeer/ai-runner:live-app-streamdiffusion
FROM ${BASE_IMAGE}

# Set initial params for infer.py via env; passed through by LiveVideoToVideoPipeline
ENV INFERPY_INITIAL_PARAMS='{\
  "model_id": "varb15/PerfectPhotonV2.1",\
  "num_inference_steps": 50,\
  "t_index_list": [5, 15, 32],\
  "controlnets": [\
    {\
      "model_id": "lllyasviel/control_v11f1p_sd15_depth",\
      "conditioning_scale": 0.0,\
      "preprocessor": "depth_tensorrt",\
      "preprocessor_params": {},\
      "enabled": true,\
      "control_guidance_start": 0.0,\
      "control_guidance_end": 1.0\
    },\
    {\
      "model_id": "lllyasviel/control_v11f1e_sd15_tile",\
      "conditioning_scale": 0.1,\
      "preprocessor": "feedback",\
      "preprocessor_params": {},\
      "enabled": true,\
      "control_guidance_start": 0.0,\
      "control_guidance_end": 1.0\
    }\
  ],\
  "ip_adapter": {"scale": 0.5, "enabled": false}\
}'

