ARG BASE_IMAGE=livepeer/ai-runner:live-base
FROM ${BASE_IMAGE}

# Install Miniconda and create the 'comfystream' environment
ARG PYTHON_VERSION=3.10
ENV CONDA_DIR /workspace/miniconda3
ENV PATH $CONDA_DIR/bin:$PATH

RUN apt-get update && apt-get install -y --no-install-recommends wget curl ca-certificates && \
    wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py310_23.11.0-2-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p $CONDA_DIR && \
    rm ~/miniconda.sh && \
    conda init bash && \
    conda config --set auto_activate_base false && \
    conda clean -a -y && \
    conda create -n comfystream python=$PYTHON_VERSION -y && \
    conda run -n comfystream pip install --no-cache-dir --upgrade pip==23.3.2 setuptools==69.5.1 wheel==0.43.0 && \
    conda clean -a -y && \
    apt-get purge -y --auto-remove wget curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PIP_PREFER_BINARY=1

# Install StreamDiffusion dependencies into the comfystream environment
RUN conda run -n comfystream pip install --no-cache-dir \
    torch==2.7.0 \
    torchvision==0.22.0 \
    xformers===0.0.30 \
    --index-url https://download.pytorch.org/whl/cu126


# Install StreamDiffusion @ b623251 (latest at time of writing) into the comfystream environment
RUN conda run -n comfystream pip install git+https://github.com/pschroedl/StreamDiffusion.git@10dbcab3c46b192992dc0440fbc75398c7fc430b#egg=streamdiffusion[tensorrt]

# Install TensorRT bindings and libraries into the comfystream environment
# TODO: update install-tensorrt script in streamdiffusion and use it instead of this
RUN conda run -n comfystream --no-capture-output pip install --upgrade tensorrt-cu12-bindings==10.9.0.34 tensorrt-cu12-libs==10.9.0.34 --root-user-action=ignore

RUN conda run -n comfystream pip install --no-cache-dir \
    onnx==1.17.0 onnxruntime==1.17.0 onnxruntime-gpu==1.20.2

RUN conda run -n comfystream pip install --no-cache-dir --force-reinstall \
    huggingface-hub==0.25.2 \
    transformers==4.38.2

WORKDIR /app

# Create symlink for where StreamDiffusion builds TensorRT engines at runtime
RUN ln -s /models/StreamDiffusion--engines ./engines
