ARG BASE_IMAGE=livepeer/ai-runner:live-base
FROM ${BASE_IMAGE}

# Install Python 3.11 via uv
RUN uv python install 3.11

# Install StreamDiffusion dependencies
RUN uv pip install --no-cache \
    torch==2.7.1+cu128 \
    torchvision==0.22.1+cu128 \
    torchaudio==2.7.1+cu128 \
    --index-url https://download.pytorch.org/whl/cu128

# Install StreamDiffusion lib
ARG STREAMDIFFUSION_VERSION=v1.0.0-rc
RUN uv pip install --no-cache "streamdiffusion[tensorrt,controlnet,ipadapter] @ git+https://github.com/daydreamlive/StreamDiffusion.git@${STREAMDIFFUSION_VERSION}"

# Install TensorRT bindings and libraries
RUN uv run python -m streamdiffusion.tools.install-tensorrt

# Enable fast HF downloads for StreamDiffusion lib, which uses older huggingface_hub version
RUN uv pip install --no-cache hf_transfer==0.1.4
ENV HF_HUB_ENABLE_HF_TRANSFER=1

WORKDIR /app

# Disable HF hub connectivity to avoid internet access during runtime.
# This is manually disabled on the script to download models (dl_checkpoints.sh)
ENV HF_HUB_OFFLINE=1

# Create symlink for where StreamDiffusion builds TensorRT engines at runtime
RUN ln -s /models/StreamDiffusion--engines ./engines
# this is required for faceid ipadapter, whose dependency instals on a fixed path
RUN mkdir -p /root && ln -s /models/insightface /root/.insightface
# this one is used only for realesrgan_trt which has ./models hardcoded
RUN ln -s /models/StreamDiffusion--models ./models
