ARG BASE_IMAGE=livepeer/ai-runner:base
FROM ${BASE_IMAGE}

# Install CUDA Toolkit to enable flash attention.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    cuda-toolkit-12-1 \
    g++ && \
    rm -rf /var/lib/apt/lists/*

# Clone Chatterbox, checkout specific commit, create pyproject.toml, and install it
RUN git clone https://huggingface.co/spaces/ResembleAI/Chatterbox /opt/Chatterbox && \
    cd /opt/Chatterbox && \
    git checkout bf4bbc30226326884e0d57b1e45ec0550683300f && \
    echo '[build-system]\nrequires = ["setuptools"]\nbuild-backend = "setuptools.build_meta"\n\n[project]\nname = "chatterbox"\nversion = "0.1.0"' > pyproject.toml && \
    pip install --no-cache-dir -e . && \    
    pip install --no-cache-dir -r requirements.txt

# Override base working directory to ensure the correct working directory.
WORKDIR /app

# Copy app directory to avoid rebuilding the base image during development.
COPY app/ /app/app

CMD ["uvicorn", "app.main:app", "--log-config", "app/cfg/uvicorn_logging_config.json", "--host", "", "--port", "8000"]
