name: 'Cleanup Runner'
description: 'Cleans up GitHub-hosted runner to free up disk space for large builds'
runs:
  using: "composite"
  steps:
    - name: Cleanup hosted runner
      shell: bash
      run: |
        # Remove unnecessary packages
        apt purge -yqq dotnet-* mono-* llvm-* libllvm* powershell* openjdk-* \
        temurin-* mongodb-* firefox mysql-* \
        hhvm google-chrome-stable \
        libgl1-mesa-dri microsoft-edge-stable azure-cli || true

        # Clean apt cache
        apt clean
        apt autoremove -y

        # Remove large directories
        rm -rf /usr/share/dotnet /usr/local/lib/android
        rm -rf /usr/local/share/chromium /usr/local/share/chrome
        rm -rf /usr/local/.ghcup /usr/local/share/powershell
        rm -rf /opt/hostedtoolcache/* /usr/local/lib/node_modules

        # Clean npm and yarn caches
        npm cache clean --force || true
        yarn cache clean || true

        # Remove Docker images and build cache
        docker system prune -af

        # Show available space after cleanup
        df -h
