name: Run AI Runner Tests

on:
  push:
    branches:
      - main
    paths:
      - "runner/**"
  pull_request:
    paths:
      - "runner/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r runner/requirements-dev.txt
          pip install -r runner/requirements.txt

      - name: Run tests
        working-directory: runner
        run: pytest
