name: Build streamdiffusion ai-runner images

on:
  pull_request:
    paths:
      - "runner/docker/Dockerfile.live-*"
      - "runner/app/**"
      - "runner/images/**"
      - "runner/VERSION"
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - "runner/docker/Dockerfile.live-*"
      - "runner/app/**"
      - "runner/images/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ !((github.ref_type == 'branch' && github.ref_name == 'main') || github.ref_type == 'tag') }}

jobs:
  base:
    name: streamdiffusion-base image
    runs-on: [self-hosted, linux, amd64]
    outputs:
      image-digest: ${{ steps.build-base.outputs.digest }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for base image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: livepeer/ai-runner
          tags: |
            type=raw,value=live-base-streamdiffusion,enable={{is_default_branch}}
            type=sha,prefix=live-base-streamdiffusion-sha-
            type=sha,format=long,prefix=live-base-streamdiffusion-sha-
            type=ref,event=pr,prefix=live-base-streamdiffusion-pr-
            type=ref,event=tag,prefix=live-base-streamdiffusion-
            type=ref,event=branch,prefix=live-base-streamdiffusion-
            type=raw,value=latest,enable={{is_default_branch}},prefix=live-base-streamdiffusion-

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CI_DOCKERHUB_TOKEN }}

      - name: Build and push live-base image
        id: build-base
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:runner"
          file: docker/Dockerfile.live-base-streamdiffusion
          provenance: mode=max
          sbom: true
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=livepeer/ai-runner:live-base-streamdiffusion-dockerbuildcache
          cache-to: type=registry,ref=livepeer/ai-runner:live-base-streamdiffusion-dockerbuildcache,mode=max

  runner:
    name: Build pipeline images (streamdiffusion variants)
    needs: base
    runs-on: [self-hosted, linux, amd64]
    strategy:
      matrix:
        include:
          - name: streamdiffusion
            image_tag_prefix: live-app-streamdiffusion
            cache_ref: livepeer/ai-runner:live-app-streamdiffusion-dockerbuildcache
            load_params: false
          - name: streamdiffusion-sd15
            image_tag_prefix: live-app-streamdiffusion-sd15
            cache_ref: livepeer/ai-runner:live-app-streamdiffusion-sd15-dockerbuildcache
            load_params: true
            params_file: runner/app/live/pipelines/streamdiffusion_sd15_default_params.json
          - name: streamdiffusion-sdxl
            image_tag_prefix: live-app-streamdiffusion-sdxl
            cache_ref: livepeer/ai-runner:live-app-streamdiffusion-sdxl-dockerbuildcache
            load_params: true
            params_file: runner/app/live/pipelines/streamdiffusion_sdxl_default_params.json
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for app image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: livepeer/ai-runner
          tags: |
            type=raw,value=${{ matrix.image_tag_prefix }},enable={{is_default_branch}}
            type=sha,prefix=${{ matrix.image_tag_prefix }}-sha-
            type=sha,format=long,prefix=${{ matrix.image_tag_prefix }}-sha-
            type=ref,event=pr,prefix=${{ matrix.image_tag_prefix }}-pr-
            type=ref,event=tag,prefix=${{ matrix.image_tag_prefix }}-
            type=ref,event=branch,prefix=${{ matrix.image_tag_prefix }}-
            type=raw,value=latest,enable={{is_default_branch}},prefix=${{ matrix.image_tag_prefix }}-

      - name: Get version information (for docker build tag)
        id: version
        run: |
          echo "version=$(bash runner/print_version.sh)" >> "$GITHUB_OUTPUT"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CI_DOCKERHUB_TOKEN }}

      - name: Load params from file (compact via tr)
        if: ${{ matrix.load_params }}
        id: params_json
        shell: bash
        run: |
          JSON_FILE="${{ matrix.params_file }}"
          JSON_COMPACT=$(tr -d '\n' < "$JSON_FILE")
          echo "json_compact=$JSON_COMPACT" >> "$GITHUB_OUTPUT"

      - name: Build and push pipeline app image
        id: build-app
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:runner"
          provenance: mode=max
          sbom: true
          push: true
          file: docker/Dockerfile.live-app__PIPELINE__
          build-args: |
            PIPELINE=streamdiffusion
            GIT_SHA=${{ (github.ref_type == 'tag' && github.ref_name) || (github.event.pull_request.head.sha || github.sha) }}
            VERSION=${{ steps.version.outputs.version }}
            # only specify base image if we just built it above, otherwise use whatever default is in the Dockerfile
            ${{ needs.base.outputs.image-digest && format('BASE_IMAGE=livepeer/ai-runner@{0}', needs.base.outputs.image-digest) }}
            ${{ matrix.load_params && format('INFERPY_INITIAL_PARAMS={0}', steps.params_json.outputs.json_compact) }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ matrix.cache_ref }}
          cache-to: type=registry,ref=${{ matrix.cache_ref }},mode=max

      - name: Notify new build upload
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
