name: Check OpenAPI spec & Golang bindings update

on:
  pull_request:

jobs:
  check-openapi-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r runner/requirements.txt

      - name: Generate AI OpenAPI specification
        run: |
          cd runner
          python gen_openapi.py
          cd $GITHUB_WORKSPACE

      - name: Check OpenAPI change
        run: |
          git diff --exit-code
          if [ $? -ne 0 ]; then
            echo "OpenAPI spec has changed. Please run 'python gen_openapi.py' and commit the changes."
            exit 1
          fi

      - name: Generate Go bindings
        run: |
          make

      - name: Check Go bindings change
        run: |
          git diff --exit-code
          if [ $? -ne 0 ]; then
            echo "Go bindings have changed. Please run 'make' and commit the changes."
            exit 1
          fi
